# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-17 15:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-posted_at']},
        ),
        migrations.AlterField(
            model_name='message',
            name='posted_at',
            field=models.DateTimeField(),
        ),
    ]
